 export const allCountries = [
  { code: "af", name: "Afghanistan", flag: "https://flagcdn.com/w320/af.png" },
  { code: "al", name: "Albania", flag: "https://flagcdn.com/w320/al.png" },
  { code: "dz", name: "Algeria", flag: "https://flagcdn.com/w320/dz.png" },
  { code: "as", name: "American Samoa", flag: "https://flagcdn.com/w320/as.png" },
  { code: "ad", name: "Andorra", flag: "https://flagcdn.com/w320/ad.png" },
  { code: "ao", name: "Angola", flag: "https://flagcdn.com/w320/ao.png" },
  { code: "ai", name: "Anguilla", flag: "https://flagcdn.com/w320/ai.png" },
  { code: "ag", name: "Antigua and Barbuda", flag: "https://flagcdn.com/w320/ag.png" },
  { code: "ar", name: "Argentina", flag: "https://flagcdn.com/w320/ar.png" },
  { code: "am", name: "Armenia", flag: "https://flagcdn.com/w320/am.png" },
  { code: "aw", name: "Aruba", flag: "https://flagcdn.com/w320/aw.png" },
  { code: "au", name: "Australia", flag: "https://flagcdn.com/w320/au.png" },
  { code: "at", name: "Austria", flag: "https://flagcdn.com/w320/at.png" },
  { code: "az", name: "Azerbaijan", flag: "https://flagcdn.com/w320/az.png" },
  { code: "bs", name: "Bahamas", flag: "https://flagcdn.com/w320/bs.png" },
  { code: "bh", name: "Bahrain", flag: "https://flagcdn.com/w320/bh.png" },
  { code: "bd", name: "Bangladesh", flag: "https://flagcdn.com/w320/bd.png" },
  { code: "bb", name: "Barbados", flag: "https://flagcdn.com/w320/bb.png" },
  { code: "by", name: "Belarus", flag: "https://flagcdn.com/w320/by.png" },
  { code: "be", name: "Belgium", flag: "https://flagcdn.com/w320/be.png" },
  { code: "bz", name: "Belize", flag: "https://flagcdn.com/w320/bz.png" },
  { code: "bj", name: "Benin", flag: "https://flagcdn.com/w320/bj.png" },
  { code: "bm", name: "Bermuda", flag: "https://flagcdn.com/w320/bm.png" },
  { code: "bt", name: "Bhutan", flag: "https://flagcdn.com/w320/bt.png" },
  { code: "bo", name: "Bolivia", flag: "https://flagcdn.com/w320/bo.png" },
  { code: "ba", name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/w320/ba.png" },
  { code: "bw", name: "Botswana", flag: "https://flagcdn.com/w320/bw.png" },
  { code: "br", name: "Brazil", flag: "https://flagcdn.com/w320/br.png" },
  { code: "bn", name: "Brunei Darussalam", flag: "https://flagcdn.com/w320/bn.png" },
  { code: "bg", name: "Bulgaria", flag: "https://flagcdn.com/w320/bg.png" },
  { code: "bf", name: "Burkina Faso", flag: "https://flagcdn.com/w320/bf.png" },
  { code: "bi", name: "Burundi", flag: "https://flagcdn.com/w320/bi.png" },
  { code: "cv", name: "Cabo Verde", flag: "https://flagcdn.com/w320/cv.png" },
  { code: "kh", name: "Cambodia", flag: "https://flagcdn.com/w320/kh.png" },
  { code: "cm", name: "Cameroon", flag: "https://flagcdn.com/w320/cm.png" },
  { code: "ca", name: "Canada", flag: "https://flagcdn.com/w320/ca.png" },
  { code: "ky", name: "Cayman Islands", flag: "https://flagcdn.com/w320/ky.png" },
  { code: "cf", name: "Central African Republic", flag: "https://flagcdn.com/w320/cf.png" },
  { code: "td", name: "Chad", flag: "https://flagcdn.com/w320/td.png" },
  { code: "cl", name: "Chile", flag: "https://flagcdn.com/w320/cl.png" },
  { code: "cn", name: "China", flag: "https://flagcdn.com/w320/cn.png" },
  { code: "co", name: "Colombia", flag: "https://flagcdn.com/w320/co.png" },
  { code: "cr", name: "Costa Rica", flag: "https://flagcdn.com/w320/cr.png" },
  { code: "hr", name: "Croatia", flag: "https://flagcdn.com/w320/hr.png" },
  { code: "cu", name: "Cuba", flag: "https://flagcdn.com/w320/cu.png" },
  { code: "cy", name: "Cyprus", flag: "https://flagcdn.com/w320/cy.png" },
  { code: "cz", name: "Czech Republic", flag: "https://flagcdn.com/w320/cz.png" },
  { code: "dk", name: "Denmark", flag: "https://flagcdn.com/w320/dk.png" },
  { code: "dj", name: "Djibouti", flag: "https://flagcdn.com/w320/dj.png" },
  { code: "dm", name: "Dominica", flag: "https://flagcdn.com/w320/dm.png" },
  { code: "do", name: "Dominican Republic", flag: "https://flagcdn.com/w320/do.png" },
  { code: "ec", name: "Ecuador", flag: "https://flagcdn.com/w320/ec.png" },
  { code: "eg", name: "Egypt", flag: "https://flagcdn.com/w320/eg.png" },
  { code: "sv", name: "El Salvador", flag: "https://flagcdn.com/w320/sv.png" },
  { code: "gq", name: "Equatorial Guinea", flag: "https://flagcdn.com/w320/gq.png" },
  { code: "er", name: "Eritrea", flag: "https://flagcdn.com/w320/er.png" },
  { code: "ee", name: "Estonia", flag: "https://flagcdn.com/w320/ee.png" },
  { code: "et", name: "Ethiopia", flag: "https://flagcdn.com/w320/et.png" },
  { code: "fk", name: "Falkland Islands", flag: "https://flagcdn.com/w320/fk.png" },
  { code: "fo", name: "Faroe Islands", flag: "https://flagcdn.com/w320/fo.png" },
  { code: "fj", name: "Fiji", flag: "https://flagcdn.com/w320/fj.png" },
  { code: "fi", name: "Finland", flag: "https://flagcdn.com/w320/fi.png" },
  { code: "fr", name: "France", flag: "https://flagcdn.com/w320/fr.png" },
  { code: "gf", name: "French Guiana", flag: "https://flagcdn.com/w320/gf.png" },
  { code: "pf", name: "French Polynesia", flag: "https://flagcdn.com/w320/pf.png" },
  { code: "ga", name: "Gabon", flag: "https://flagcdn.com/w320/ga.png" },
  { code: "gm", name: "Gambia", flag: "https://flagcdn.com/w320/gm.png" },
  { code: "ge", name: "Georgia", flag: "https://flagcdn.com/w320/ge.png" },
  { code: "de", name: "Germany", flag: "https://flagcdn.com/w320/de.png" },
  { code: "gh", name: "Ghana", flag: "https://flagcdn.com/w320/gh.png" },
  { code: "gi", name: "Gibraltar", flag: "https://flagcdn.com/w320/gi.png" },
  { code: "gr", name: "Greece", flag: "https://flagcdn.com/w320/gr.png" },
  { code: "gl", name: "Greenland", flag: "https://flagcdn.com/w320/gl.png" },
  { code: "gd", name: "Grenada", flag: "https://flagcdn.com/w320/gd.png" },
  { code: "gp", name: "Guadeloupe", flag: "https://flagcdn.com/w320/gp.png" },
  { code: "gu", name: "Guam", flag: "https://flagcdn.com/w320/gu.png" },
  { code: "gt", name: "Guatemala", flag: "https://flagcdn.com/w320/gt.png" },
  { code: "gn", name: "Guinea", flag: "https://flagcdn.com/w320/gn.png" },
  { code: "gw", name: "Guinea-Bissau", flag: "https://flagcdn.com/w320/gw.png" },
  { code: "gy", name: "Guyana", flag: "https://flagcdn.com/w320/gy.png" },
  { code: "ht", name: "Haiti", flag: "https://flagcdn.com/w320/ht.png" },
  { code: "hn", name: "Honduras", flag: "https://flagcdn.com/w320/hn.png" },
  { code: "hk", name: "Hong Kong", flag: "https://flagcdn.com/w320/hk.png" },
  { code: "hu", name: "Hungary", flag: "https://flagcdn.com/w320/hu.png" },
  { code: "is", name: "Iceland", flag: "https://flagcdn.com/w320/is.png" },
  { code: "in", name: "India", flag: "https://flagcdn.com/w320/in.png" },
  { code: "id", name: "Indonesia", flag: "https://flagcdn.com/w320/id.png" },
  { code: "ir", name: "Iran", flag: "https://flagcdn.com/w320/ir.png" },
  { code: "iq", name: "Iraq", flag: "https://flagcdn.com/w320/iq.png" },
  { code: "ie", name: "Ireland", flag: "https://flagcdn.com/w320/ie.png" },
  { code: "il", name: "Israel", flag: "https://flagcdn.com/w320/il.png" },
  { code: "it", name: "Italy", flag: "https://flagcdn.com/w320/it.png" },
  { code: "jm", name: "Jamaica", flag: "https://flagcdn.com/w320/jm.png" },
  { code: "jp", name: "Japan", flag: "https://flagcdn.com/w320/jp.png" },
  { code: "jo", name: "Jordan", flag: "https://flagcdn.com/w320/jo.png" },
  { code: "kz", name: "Kazakhstan", flag: "https://flagcdn.com/w320/kz.png" },
  { code: "ke", name: "Kenya", flag: "https://flagcdn.com/w320/ke.png" },
  { code: "ki", name: "Kiribati", flag: "https://flagcdn.com/w320/ki.png" },
  { code: "kp", name: "North Korea", flag: "https://flagcdn.com/w320/kp.png" },
  { code: "kr", name: "South Korea", flag: "https://flagcdn.com/w320/kr.png" },
  { code: "kw", name: "Kuwait", flag: "https://flagcdn.com/w320/kw.png" },
  { code: "kg", name: "Kyrgyzstan", flag: "https://flagcdn.com/w320/kg.png" },
  { code: "la", name: "Laos", flag: "https://flagcdn.com/w320/la.png" },
  { code: "lv", name: "Latvia", flag: "https://flagcdn.com/w320/lv.png" },
  { code: "lb", name: "Lebanon", flag: "https://flagcdn.com/w320/lb.png" },
  { code: "ls", name: "Lesotho", flag: "https://flagcdn.com/w320/ls.png" },
  { code: "lr", name: "Liberia", flag: "https://flagcdn.com/w320/lr.png" },
  { code: "li", name: "Liechtenstein", flag: "https://flagcdn.com/w320/li.png" },
  { code: "lt", name: "Lithuania", flag: "https://flagcdn.com/w320/lt.png" },
  { code: "lu", name: "Luxembourg", flag: "https://flagcdn.com/w320/lu.png" },
  { code: "mo", name: "Macau", flag: "https://flagcdn.com/w320/mo.png" },
  { code: "mk", name: "North Macedonia", flag: "https://flagcdn.com/w320/mk.png" },
  { code: "mg", name: "Madagascar", flag: "https://flagcdn.com/w320/mg.png" },
  { code: "mw", name: "Malawi", flag: "https://flagcdn.com/w320/mw.png" },
  { code: "my", name: "Malaysia", flag: "https://flagcdn.com/w320/my.png" },
  { code: "mv", name: "Maldives", flag: "https://flagcdn.com/w320/mv.png" },
  { code: "ml", name: "Mali", flag: "https://flagcdn.com/w320/ml.png" },
  { code: "mt", name: "Malta", flag: "https://flagcdn.com/w320/mt.png" },
  { code: "mh", name: "Marshall Islands", flag: "https://flagcdn.com/w320/mh.png" },
  { code: "mq", name: "Martinique", flag: "https://flagcdn.com/w320/mq.png" },
  { code: "mr", name: "Mauritania", flag: "https://flagcdn.com/w320/mr.png" },
  { code: "mu", name: "Mauritius", flag: "https://flagcdn.com/w320/mu.png" },
  { code: "yt", name: "Mayotte", flag: "https://flagcdn.com/w320/yt.png" },
  { code: "mx", name: "Mexico", flag: "https://flagcdn.com/w320/mx.png" },
  { code: "fm", name: "Micronesia", flag: "https://flagcdn.com/w320/fm.png" },
  { code: "md", name: "Moldova", flag: "https://flagcdn.com/w320/md.png" },
  { code: "mc", name: "Monaco", flag: "https://flagcdn.com/w320/mc.png" },
  { code: "mn", name: "Mongolia", flag: "https://flagcdn.com/w320/mn.png" },
  { code: "me", name: "Montenegro", flag: "https://flagcdn.com/w320/me.png" },
  { code: "ms", name: "Montserrat", flag: "https://flagcdn.com/w320/ms.png" },
  { code: "ma", name: "Morocco", flag: "https://flagcdn.com/w320/ma.png" },
  { code: "mz", name: "Mozambique", flag: "https://flagcdn.com/w320/mz.png" },
  { code: "mm", name: "Myanmar", flag: "https://flagcdn.com/w320/mm.png" },
  { code: "na", name: "Namibia", flag: "https://flagcdn.com/w320/na.png" },
  { code: "nr", name: "Nauru", flag: "https://flagcdn.com/w320/nr.png" },
  { code: "np", name: "Nepal", flag: "https://flagcdn.com/w320/np.png" },
  { code: "nl", name: "Netherlands", flag: "https://flagcdn.com/w320/nl.png" },
  { code: "nc", name: "New Caledonia", flag: "https://flagcdn.com/w320/nc.png" },
  { code: "nz", name: "New Zealand", flag: "https://flagcdn.com/w320/nz.png" },
  { code: "ni", name: "Nicaragua", flag: "https://flagcdn.com/w320/ni.png" },
  { code: "ne", name: "Niger", flag: "https://flagcdn.com/w320/ne.png" },
  { code: "ng", name: "Nigeria", flag: "https://flagcdn.com/w320/ng.png" },
  { code: "nu", name: "Niue", flag: "https://flagcdn.com/w320/nu.png" },
  { code: "nf", name: "Norfolk Island", flag: "https://flagcdn.com/w320/nf.png" },
  { code: "mp", name: "Northern Mariana Islands", flag: "https://flagcdn.com/w320/mp.png" },
  { code: "no", name: "Norway", flag: "https://flagcdn.com/w320/no.png" },
  { code: "om", name: "Oman", flag: "https://flagcdn.com/w320/om.png" },
  { code: "pk", name: "Pakistan", flag: "https://flagcdn.com/w320/pk.png" },
  { code: "pw", name: "Palau", flag: "https://flagcdn.com/w320/pw.png" },
  { code: "pa", name: "Panama", flag: "https://flagcdn.com/w320/pa.png" },
  { code: "pg", name: "Papua New Guinea", flag: "https://flagcdn.com/w320/pg.png" },
  { code: "py", name: "Paraguay", flag: "https://flagcdn.com/w320/py.png" },
  { code: "pe", name: "Peru", flag: "https://flagcdn.com/w320/pe.png" },
  { code: "ph", name: "Philippines", flag: "https://flagcdn.com/w320/ph.png" },
  { code: "pn", name: "Pitcairn Islands", flag: "https://flagcdn.com/w320/pn.png" },
  { code: "pl", name: "Poland", flag: "https://flagcdn.com/w320/pl.png" },
  { code: "pt", name: "Portugal", flag: "https://flagcdn.com/w320/pt.png" },
  { code: "pr", name: "Puerto Rico", flag: "https://flagcdn.com/w320/pr.png" },
  { code: "qa", name: "Qatar", flag: "https://flagcdn.com/w320/qa.png" },
  { code: "re", name: "Réunion", flag: "https://flagcdn.com/w320/re.png" },
  { code: "ro", name: "Romania", flag: "https://flagcdn.com/w320/ro.png" },
  { code: "ru", name: "Russia", flag: "https://flagcdn.com/w320/ru.png" },
  { code: "rw", name: "Rwanda", flag: "https://flagcdn.com/w320/rw.png" },
  { code: "ws", name: "Samoa", flag: "https://flagcdn.com/w320/ws.png" },
  { code: "sm", name: "San Marino", flag: "https://flagcdn.com/w320/sm.png" },
  { code: "st", name: "São Tomé and Príncipe", flag: "https://flagcdn.com/w320/st.png" },
  { code: "sa", name: "Saudi Arabia", flag: "https://flagcdn.com/w320/sa.png" },
  { code: "sn", name: "Senegal", flag: "https://flagcdn.com/w320/sn.png" },
  { code: "rs", name: "Serbia", flag: "https://flagcdn.com/w320/rs.png" },
  { code: "sc", name: "Seychelles", flag: "https://flagcdn.com/w320/sc.png" },
  { code: "sl", name: "Sierra Leone", flag: "https://flagcdn.com/w320/sl.png" },
  { code: "sg", name: "Singapore", flag: "https://flagcdn.com/w320/sg.png" },
  { code: "sx", name: "Sint Maarten", flag: "https://flagcdn.com/w320/sx.png" },
  { code: "sk", name: "Slovakia", flag: "https://flagcdn.com/w320/sk.png" },
  { code: "si", name: "Slovenia", flag: "https://flagcdn.com/w320/si.png" },
  { code: "sb", name: "Solomon Islands", flag: "https://flagcdn.com/w320/sb.png" },
  { code: "so", name: "Somalia", flag: "https://flagcdn.com/w320/so.png" },
  { code: "za", name: "South Africa", flag: "https://flagcdn.com/w320/za.png" },
  { code: "ss", name: "South Sudan", flag: "https://flagcdn.com/w320/ss.png" },
  { code: "es", name: "Spain", flag: "https://flagcdn.com/w320/es.png" },
  { code: "lk", name: "Sri Lanka", flag: "https://flagcdn.com/w320/lk.png" },
  { code: "sd", name: "Sudan", flag: "https://flagcdn.com/w320/sd.png" },
  { code: "sr", name: "Suriname", flag: "https://flagcdn.com/w320/sr.png" },
  { code: "sz", name: "Eswatini", flag: "https://flagcdn.com/w320/sz.png" },
  { code: "se", name: "Sweden", flag: "https://flagcdn.com/w320/se.png" },
  { code: "ch", name: "Switzerland", flag: "https://flagcdn.com/w320/ch.png" },
  { code: "sy", name: "Syria", flag: "https://flagcdn.com/w320/sy.png" },
  { code: "tw", name: "Taiwan", flag: "https://flagcdn.com/w320/tw.png" },
  { code: "tj", name: "Tajikistan", flag: "https://flagcdn.com/w320/tj.png" },
  { code: "tz", name: "Tanzania", flag: "https://flagcdn.com/w320/tz.png" },
  { code: "th", name: "Thailand", flag: "https://flagcdn.com/w320/th.png" },
  { code: "tl", name: "Timor-Leste", flag: "https://flagcdn.com/w320/tl.png" },
  { code: "tg", name: "Togo", flag: "https://flagcdn.com/w320/tg.png" },
  { code: "tk", name: "Tokelau", flag: "https://flagcdn.com/w320/tk.png" },
  { code: "to", name: "Tonga", flag: "https://flagcdn.com/w320/to.png" },
  { code: "tt", name: "Trinidad and Tobago", flag: "https://flagcdn.com/w320/tt.png" },
  { code: "tn", name: "Tunisia", flag: "https://flagcdn.com/w320/tn.png" },
  { code: "tr", name: "Turkey", flag: "https://flagcdn.com/w320/tr.png" },
  { code: "tm", name: "Turkmenistan", flag: "https://flagcdn.com/w320/tm.png" },
  { code: "tc", name: "Turks and Caicos Islands", flag: "https://flagcdn.com/w320/tc.png" },
  { code: "tv", name: "Tuvalu", flag: "https://flagcdn.com/w320/tv.png" },
  { code: "ug", name: "Uganda", flag: "https://flagcdn.com/w320/ug.png" },
  { code: "ua", name: "Ukraine", flag: "https://flagcdn.com/w320/ua.png" },
  { code: "ae", name: "United Arab Emirates", flag: "https://flagcdn.com/w320/ae.png" },
  { code: "gb", name: "United Kingdom", flag: "https://flagcdn.com/w320/gb.png" },
  { code: "us", name: "United States", flag: "https://flagcdn.com/w320/us.png" },
  { code: "uy", name: "Uruguay", flag: "https://flagcdn.com/w320/uy.png" },
  { code: "uz", name: "Uzbekistan", flag: "https://flagcdn.com/w320/uz.png" },
  { code: "vu", name: "Vanuatu", flag: "https://flagcdn.com/w320/vu.png" },
  { code: "va", name: "Vatican City", flag: "https://flagcdn.com/w320/va.png" },
  { code: "ve", name: "Venezuela", flag: "https://flagcdn.com/w320/ve.png" },
  { code: "vn", name: "Vietnam", flag: "https://flagcdn.com/w320/vn.png" },
  { code: "wf", name: "Wallis and Futuna", flag: "https://flagcdn.com/w320/wf.png" },
  { code: "eh", name: "Western Sahara", flag: "https://flagcdn.com/w320/eh.png" },
  { code: "ye", name: "Yemen", flag: "https://flagcdn.com/w320/ye.png" },
  { code: "zm", name: "Zambia", flag: "https://flagcdn.com/w320/zm.png" },
  { code: "zw", name: "Zimbabwe", flag: "https://flagcdn.com/w320/zw.png" }
];

export const getFlagUrl = (countryCode = "") => {
    const code = countryCode.toLowerCase()
  const country = allCountries.find((country) => country.code === code);
  return country ? country.flag : 'Country code not found';
};